spring:
  datasource:
    url : jdbc:mariadb://localhost:3306/test_db
    username: root
    password: 1q2w3e4r
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG

server:
  tomcat:
    max-threads: 100